version: '3.1'

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:arm32v7-latest
    container_name: heimdall
    environment:
      - TZ=Europe/Madrid
    volumes:
      - data:/config
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  data:

