version: '3.1'

services:
  transmission:
    image: linuxserver/transmission:arm32v7-latest
    container_name: transmission
    environment:
      - TZ=Europe/Madrid
      - TRANSMISSION_WEB_HOME=/kettu/ # /combustion-release/ ; /kettu/
      - PUID=1000
      - PGID=1000 
    volumes:
      - data:/config
      - /media/hd/downloads:/downloads
      - /media/hd/downloads/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

volumes:
  data:

